<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "consent_banner"
 *
 * Auto generated by Extension Builder 2019-12-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Consent Banner',
    'description' => 'Consent Banner Extension with Javascript.',
    'category' => 'fe',
    'author' => 'Andreas Schulze',
    'author_company' => 'berbach GmbH',
    'author_email' => 'schulze@berbach.de',
    'state' => 'stable',
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'php' => '8.4.0-8.5.99',
            'typo3' => '13.4.1-13.99.99',
            'backend' => '13.4.1-13.99.99',
            'extbase' => '13.4.1-13.99.99',
            'fluid' => '13.4.1-13.99.99',
            'frontend' => '13.4.1-13.99.99',
        ],
        'conflicts' => []
    ]
];
