<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "consent_banner"
 *
 * Auto generated by Extension Builder 2019-12-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Consent Banner',
    'description' => 'Consent Banner Extension with Javascript and non-Javascript.',
    'category' => 'plugin',
    'author' => 'Andreas Schulze',
    'author_company' => 'berbach GmbH',
    'author_email' => 'schulze@berbach.de',
    'dependencies' => 'extbase,fluid',
    'state' => 'stable',
    'clearCacheOnLoad' => '1',
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '11.5.19-12.9.99',
            'extbase' => '11.5.19-12.9.99',
            'fluid' => '11.5.19-12.9.99',
            'php' => '7.4.0-8.2.99',
        ],
        'conflicts' => []
    ]
];
